/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/pylonv1.glb --transform 
Files: public/pylonv1.glb [8.27KB] > C:\Users\barte\Documents\VS-code\js-creator\generator-liter-3d\pylonv1-transformed.glb [2.08KB] (75%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/pylonv1-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.empty_2.geometry} material={nodes.empty_2.material} />
      <mesh geometry={nodes.empty_4.geometry} material={nodes.empty_4.material} />
    </group>
  )
}

useGLTF.preload('/pylonv1-transformed.glb')
