/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/pylon.glb --transform 
Files: public/pylon.glb [8.29KB] > C:\Users\barte\Documents\VS-code\js-creator\generator-liter-3d\pylon-transformed.glb [1.38KB] (83%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/pylon-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.empty_2.geometry} material={nodes.empty_2.material} />
      
    </group>
  )
}

useGLTF.preload('/pylon-transformed.glb')
