/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/SF.glb --transform 
Files: public/SF.glb [28.73KB] > C:\Users\barte\Documents\VS-code\js-creator\generator-liter-3d\SF-transformed.glb [3.25KB] (89%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/SF-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.SMARTFRAME_v1.geometry} material={materials['Stal_—_satynowa']} />
      <mesh geometry={nodes.Płaszczyzna.geometry} material={nodes.Płaszczyzna.material} />
    </group>
  )
}

useGLTF.preload('/SF-transformed.glb')
