/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/untitled.glb --transform 
Files: public/untitled.glb [28.81KB] > C:\Users\barte\Documents\VS-code\js-creator\generator-liter-3d\untitled-transformed.glb [3.32KB] (88%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/untitled-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.SMARTFRAME_v1.geometry} material={materials['Stal_—_satynowa']} />
      <mesh geometry={nodes.Płaszczyzna.geometry} material={nodes.Płaszczyzna.material} position={[23.501, 40.075, -1.204]} rotation={[-Math.PI / 2, 0, 0]} scale={[22.216, 1, 32.189]} />
    </group>
  )
}

useGLTF.preload('/untitled-transformed.glb')
